name = "Compile"
version = "0.1.0"
defaultTargets = ["CompileLean"]

[[lean_lib]]
name = "CompileLean"

[[lean_lib]]
name = "CompileMathlib"

[[lean_lib]]
name = "CompileFLT"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.26.0"

[[require]]
name = "flt"
git = "https://github.com/ImperialCollegeLondon/FLT"
rev = "v4.26.0"
