name = "CompileFC"
version = "0.1.0"
defaultTargets = ["compile-fc"]

[[lean_lib]]
name = "CompileFC"

[[lean_exe]]
name = "compile-fc"
root = "Main"

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "20af7726bba72fc97d8feda6958a8afacc664ad4"

[[require]]
name = "ix"
path = "../.."
