name: Blake3 bench

on:
  push:
    branches: ci-bench-blake3
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lean-jobs:
    runs-on: gh-64vcpu-256gbram-ubuntu-2404
    steps:
      - uses: actions/checkout@v6
      - uses: leanprover/lean-action@v1 # https://github.com/leanprover/lean-action
        with:
          build-args: "--wfail -v"
          test: false
      - run: lake exe bench-blake3
